RUBRIC_BUNDLE = {
    "rubric_version": "story_quality_v1",
    "scale": {
        "type": "ordinal",
        "min": 0,
        "max": 5,
        "display_mapping": "score_100 = round(score_0_5 / 5 * 100)",
    },
    "global_rules": [
        "Use only the provided script text and line ids.",
        "Do not invent backstory or subtext unless explicitly stated.",
        "Every score must cite at least one line id.",
        "Scores above 3 should usually cite two or more line ids.",
        "If evidence is sparse or ambiguous, lower confidence.",
        "A score of 5 is exceptional for this criterion, not merely good.",
        "A score of 0 means absent or actively harmful for this criterion.",
        "Return JSON only.",
    ],
    "dimensions": [
        {
            "name": "hook_strength",
            "weight": 0.20,
            "definition": "How strongly the opening creates immediate curiosity, tension, surprise, or emotional pull.",
            "score_anchors": {
                "0": "Flat opening. No curiosity, tension, or reason to continue.",
                "1": "Weak opening. Situation is presented but interest is low.",
                "2": "Some setup value, but limited urgency or intrigue.",
                "3": "Solid opening. Clear reason to keep watching.",
                "4": "Strong opening. Immediate tension, surprise, or compelling question.",
                "5": "Exceptional opening. Hard to stop reading after the first lines.",
            },
        },
        {
            "name": "conflict_clarity",
            "weight": 0.20,
            "definition": "How clearly the scene establishes interpersonal, internal, or situational conflict.",
            "score_anchors": {
                "0": "No meaningful conflict.",
                "1": "Conflict is hinted at but too vague to matter.",
                "2": "Conflict exists but lacks sharpness or friction.",
                "3": "Clear conflict with understandable tension.",
                "4": "Strong conflict with active friction between characters or goals.",
                "5": "Exceptionally sharp conflict that drives every beat.",
            },
        },
        {
            "name": "escalation",
            "weight": 0.15,
            "definition": "How well the scene increases pressure, stakes, danger, emotional intensity, or urgency over time.",
            "score_anchors": {
                "0": "No escalation. Scene is static.",
                "1": "Very minor change, mostly flat.",
                "2": "Some movement, but pressure barely rises.",
                "3": "Noticeable escalation through the scene.",
                "4": "Strong escalation with clear beat-to-beat increase in tension or stakes.",
                "5": "Excellent escalation. Each beat meaningfully tightens the scene.",
            },
        },
        {
            "name": "emotional_specificity",
            "weight": 0.15,
            "definition": "How vivid, specific, and believable the emotional experience feels.",
            "score_anchors": {
                "0": "Emotion is absent or generic.",
                "1": "Emotion is named or implied but feels thin.",
                "2": "Some emotional texture, but broad or cliche.",
                "3": "Clear emotional reality with some specificity.",
                "4": "Strong emotional specificity that feels lived-in and believable.",
                "5": "Exceptional emotional precision. The scene feels sharply human and memorable.",
            },
        },
        {
            "name": "dialogue_sharpness",
            "weight": 0.10,
            "definition": "How effective the dialogue is in carrying character, conflict, subtext, rhythm, and tension.",
            "score_anchors": {
                "0": "Dialogue is unnatural, flat, or damaging.",
                "1": "Mostly functional and generic.",
                "2": "Usable dialogue with some weak or obvious lines.",
                "3": "Good dialogue that supports scene goals.",
                "4": "Strong dialogue with character voice and tension.",
                "5": "Exceptional dialogue. Memorable, economical, and charged.",
            },
        },
        {
            "name": "curiosity_cliffhanger",
            "weight": 0.20,
            "definition": "How strongly the scene leaves the audience wanting the next beat, answer, or reveal.",
            "score_anchors": {
                "0": "No curiosity or cliffhanger.",
                "1": "Minimal carry-forward interest.",
                "2": "Some unresolved element, but not very compelling.",
                "3": "Clear open question or unresolved tension.",
                "4": "Strong cliffhanger or strong forward pull.",
                "5": "Exceptional ending pull. The audience urgently wants the next scene.",
            },
        },
    ],
}
