RUBRIC_BUNDLE = {
    "rubric_version": "engagement_v1",
    "scale": {
        "type": "ordinal",
        "min": 0,
        "max": 10,
        "display_mapping": "weighted_score = score * weight * 10; overall_score = sum(weighted_score)",
    },
    "global_rules": [
        "Use only the provided script text and line ids.",
        "Do not invent backstory or subtext unless explicitly stated.",
        "Every score must cite at least one line id.",
        "Scores above 6 should usually cite two or more line ids.",
        "If evidence is sparse or ambiguous, lower confidence.",
        "A score of 10 is exceptional for this criterion, not merely good.",
        "A score of 0 means absent or actively harmful for this criterion.",
        "Return JSON only.",
    ],
    "dimensions": [
        {
            "name": "opening_hook",
            "weight": 0.20,
            "definition": "How strongly the opening creates immediate curiosity, tension, surprise, or emotional pull.",
            "score_anchors": {
                "0": "Flat opening. No curiosity, tension, or reason to continue.",
                "3": "Some setup value, but limited urgency or intrigue.",
                "6": "Solid opening. Clear reason to keep watching.",
                "8": "Strong opening. Immediate tension, surprise, or compelling question.",
                "10": "Exceptional opening. Hard to stop reading after the first lines.",
            },
        },
        {
            "name": "character_conflict",
            "weight": 0.20,
            "definition": "How clearly the scene establishes interpersonal, internal, or situational conflict.",
            "score_anchors": {
                "0": "No meaningful conflict.",
                "3": "Conflict is hinted at but too vague to matter.",
                "6": "Clear conflict with understandable tension.",
                "8": "Strong conflict with active friction between characters or goals.",
                "10": "Exceptionally sharp conflict that drives every beat.",
            },
        },
        {
            "name": "tension_escalation",
            "weight": 0.15,
            "definition": "How well the scene increases pressure, stakes, danger, emotional intensity, or urgency over time.",
            "score_anchors": {
                "0": "No escalation. Scene is static.",
                "3": "Some movement, but pressure barely rises.",
                "6": "Noticeable escalation through the scene.",
                "8": "Strong escalation with clear beat-to-beat increase in tension or stakes.",
                "10": "Excellent escalation. Each beat meaningfully tightens the scene.",
            },
        },
        {
            "name": "clarity_of_stakes",
            "weight": 0.05,
            "definition": "How clearly the scene communicates what is at risk (emotionally, relationally, practically) right now.",
            "score_anchors": {
                "0": "No meaningful stakes are communicated.",
                "3": "Something is at stake, but it is vague or implied only.",
                "6": "Stakes are clear enough to understand why the moment matters.",
                "8": "Stakes are sharp and felt. The scene has a clear pressure point.",
                "10": "Stakes are immediate, specific, and hard to ignore.",
            },
        },
        {
            "name": "novelty_of_reveal",
            "weight": 0.05,
            "definition": "How fresh, surprising, or meaningfully reframing the key reveal/turn feels.",
            "score_anchors": {
                "0": "No reveal or turn.",
                "3": "A small turn, but predictable.",
                "6": "A solid reveal or turn that changes how we read the moment.",
                "8": "A strong, story-driving reveal that reframes assumptions.",
                "10": "A genuinely surprising reveal that still feels earned by the text.",
            },
        },
        {
            "name": "emotional_payoff",
            "weight": 0.15,
            "definition": "How vivid, specific, and believable the emotional impact and payoff feels.",
            "score_anchors": {
                "0": "Emotion is absent or generic.",
                "3": "Emotion is named or implied but feels thin.",
                "6": "Clear emotional reality with some specificity.",
                "8": "Strong emotional payoff that feels lived-in and believable.",
                "10": "Exceptional emotional precision. The scene feels sharply human and memorable.",
            },
        },
        {
            "name": "cliffhanger_strength",
            "weight": 0.20,
            "definition": "How strongly the scene ends with forward pull - a question, reveal, or tension that demands the next beat.",
            "score_anchors": {
                "0": "No carry-forward interest.",
                "3": "Some unresolved element, but not very compelling.",
                "6": "Clear open question or unresolved tension.",
                "8": "Strong cliffhanger or strong forward pull.",
                "10": "Exceptional ending pull. The audience urgently wants the next scene.",
            },
        },
    ],
}
